import type { Destination } from './database.types';

export const mockDestinations: Destination[] = [
  {
    id: 'mock-1',
    name: 'Tokyo & Kyoto',
    country: 'Japon',
    description:
      'Un voyage inoubliable entre modernité et tradition japonaise. Découvrez la frénésie de Tokyo, ses gratte-ciels illuminés, ses quartiers branchés comme Shibuya et Shinjuku, puis plongez dans l\'atmosphère sereine de Kyoto avec ses temples millénaires, ses geishas et ses jardins zen. Ce circuit vous offre une immersion totale dans la culture japonaise, de la cérémonie du thé aux bains thermaux onsen, en passant par la gastronomie locale exceptionnelle.',
    short_description:
      'De la frénésie de Tokyo à la sérénité de Kyoto, vivez le Japon dans toute sa splendeur entre temples anciens et néons futuristes.',
    price: 2890,
    duration_days: 14,
    image_url: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg',
    gallery_urls: [
      'https://images.pexels.com/photos/1440476/pexels-photo-1440476.jpeg',
      'https://images.pexels.com/photos/590478/pexels-photo-590478.jpeg',
      'https://images.pexels.com/photos/2070485/pexels-photo-2070485.jpeg',
      'https://images.pexels.com/photos/1398761/pexels-photo-1398761.jpeg',
    ],
    highlights: [
      'Visite du mont Fuji',
      'Cérémonie du thé traditionnelle',
      'Quartier de Gion à Kyoto',
      'Shibuya crossing de nuit',
      'Bains thermaux onsen',
      'Cours de cuisine japonaise',
    ],
    program: [
      { day: 1, title: 'Arrivée à Tokyo', description: 'Accueil à l\'aéroport de Narita, transfert à l\'hôtel et première découverte du quartier de Shinjuku.' },
      { day: 2, title: 'Tokyo - Shibuya & Harajuku', description: 'Visite du célèbre carrefour de Shibuya, shopping à Harajuku et découverte de la rue Takeshita.' },
      { day: 3, title: 'Tokyo - Asakusa & Akihabara', description: 'Temple Senso-ji, marché Nakamise et quartier électronique d\'Akihabara.' },
      { day: 4, title: 'Excursion Mont Fuji', description: 'Journée au lac Kawaguchiko avec vue imprenable sur le mont Fuji et les alentours.' },
      { day: 5, title: 'Tokyo - Musées & Culture', description: 'Musée national de Tokyo, parc Ueno et quartier de Yanaka.' },
      { day: 6, title: 'Shinkansen vers Kyoto', description: 'Trajet en bullet train, arrivée à Kyoto et visite du temple Fushimi Inari.' },
      { day: 7, title: 'Kyoto - Gion & Temples', description: 'Quartier de Gion, temple Kinkaku-ji (Pavillon d\'Or) et jardins Ryoan-ji.' },
      { day: 8, title: 'Nara & Osaka', description: 'Cerfs sacrés de Nara, grand Bouddha et soirée à Osaka.' },
      { day: 9, title: 'Osaka - Gastronomie', description: 'Quartier Dotonbori, cours de cuisine japonaise et vie nocturne.' },
      { day: 10, title: 'Kyoto - Arashiyama', description: 'Forêt de bambous, temple Tenryu-ji et balade en barque.' },
      { day: 11, title: 'Onsen & Détente', description: 'Séjour dans un ryokan traditionnel avec bains thermaux.' },
      { day: 12, title: 'Hiroshima & Miyajima', description: 'Mémorial de la paix et île sacrée de Miyajima avec son torii sur l\'eau.' },
      { day: 13, title: 'Retour à Tokyo', description: 'Dernière journée shopping à Ginza, Harajuku et préparatifs de départ.' },
      { day: 14, title: 'Départ', description: 'Transfert à l\'aéroport et envol vers la France.' },
    ],
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'mock-2',
    name: 'Bali Authentique',
    country: 'Indonésie',
    description:
      'L\'île des dieux vous accueille dans toute sa magie. Bali est une destination unique qui allie spiritualité hindoue, rizières en terrasses à couper le souffle, temples anciens et plages paradisiaques. Ce séjour vous permettra de vous reconnecter avec vous-même lors de séances de yoga au lever du soleil, de participer à des cérémonies locales, d\'explorer les villages d\'artisans d\'Ubud et de vous détendre sur les plages de sable blanc de Seminyak et Nusa Dua.',
    short_description:
      'Plongez dans la spiritualité et les paysages enchanteurs de Bali, entre rizières, temples et plages de rêve.',
    price: 1890,
    duration_days: 10,
    image_url: 'https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg',
    gallery_urls: [
      'https://images.pexels.com/photos/3225531/pexels-photo-3225531.jpeg',
      'https://images.pexels.com/photos/2474689/pexels-photo-2474689.jpeg',
      'https://images.pexels.com/photos/2108839/pexels-photo-2108839.jpeg',
    ],
    highlights: [
      'Rizières en terrasses de Tegalalang',
      'Temple de Tanah Lot au coucher du soleil',
      'Cours de cuisine balinaise',
      'Séance de yoga au lever du soleil',
      'Cérémonie traditionnelle',
      'Snorkeling à Nusa Penida',
    ],
    program: [
      { day: 1, title: 'Arrivée à Bali', description: 'Accueil à l\'aéroport de Ngurah Rai, transfert à Ubud et installation dans votre villa.' },
      { day: 2, title: 'Ubud - Art & Culture', description: 'Marché artisanal d\'Ubud, palais royal et spectacle de danse Kecak.' },
      { day: 3, title: 'Rizières & Temples', description: 'Rizières de Tegalalang, temple Tirta Empul et ses sources sacrées.' },
      { day: 4, title: 'Volcan Batur', description: 'Lever de soleil depuis le cratère du Batur avec vue sur le lac.' },
      { day: 5, title: 'Cours de Cuisine', description: 'Cours de cuisine balinaise au marché et visite d\'une plantation de café.' },
      { day: 6, title: 'Côte Ouest & Tanah Lot', description: 'Temple de Tanah Lot au coucher du soleil et plages de Canggu.' },
      { day: 7, title: 'Nusa Penida', description: 'Excursion en bateau, snorkeling et plage de Kelingking.' },
      { day: 8, title: 'Seminyak & Détente', description: 'Plages de Seminyak, spa et massage balinais traditionnel.' },
      { day: 9, title: 'Journée libre', description: 'Shopping à Kuta, dernières découvertes et soirée d\'au revoir.' },
      { day: 10, title: 'Départ', description: 'Transfert à l\'aéroport et retour vers la France.' },
    ],
    is_featured: true,
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'mock-3',
    name: 'Vietnam du Nord au Sud',
    country: 'Vietnam',
    description:
      'Un voyage épique à travers le Vietnam, de la baie d\'Ha Long aux rizières de Sapa, en passant par l\'ancienne capitale de Hué et la ville historique de Hoi An. Le Vietnam est un pays de contrastes fascinants où cohabitent traditions millénaires et modernité dynamique. Vous découvrirez une gastronomie extraordinaire, des paysages naturels à couper le souffle et un peuple chaleureux et accueillant.',
    short_description:
      'Explorez le Vietnam de Hanoi à Ho Chi Minh-Ville, entre baie d\'Ha Long, rizières et villes historiques.',
    price: 2290,
    duration_days: 16,
    image_url: 'https://images.pexels.com/photos/1603650/pexels-photo-1603650.jpeg',
    gallery_urls: [
      'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg',
      'https://images.pexels.com/photos/2549018/pexels-photo-2549018.jpeg',
      'https://images.pexels.com/photos/1483024/pexels-photo-1483024.jpeg',
    ],
    highlights: [
      'Croisière dans la baie d\'Ha Long',
      'Rizières en terrasses de Sapa',
      'Vieille ville de Hoi An la nuit',
      'Tunnels de Cu Chi',
      'Cuisine de rue à Hanoi',
      'Delta du Mékong',
    ],
    program: [
      { day: 1, title: 'Arrivée à Hanoi', description: 'Découverte du vieux quartier et du lac Hoan Kiem.' },
      { day: 2, title: 'Hanoi - Culture & Histoire', description: 'Mausolée de Ho Chi Minh, temple de la Littérature et musée d\'ethnologie.' },
      { day: 3, title: 'Baie d\'Ha Long - Embarquement', description: 'Croisière dans la baie, kayak entre les rochers karstiques.' },
      { day: 4, title: 'Baie d\'Ha Long - Exploration', description: 'Grottes, villages flottants et lever de soleil sur la baie.' },
      { day: 5, title: 'Sapa - Trek', description: 'Trek dans les rizières en terrasses, rencontre avec les ethnies locales.' },
      { day: 6, title: 'Sapa - Villages Hmong', description: 'Visite des villages de Cat Cat et Ta Van.' },
      { day: 7, title: 'Vol vers Hué', description: 'Citadelle impériale, tombeaux des empereurs.' },
      { day: 8, title: 'Hué - Pagodes & Cuisine', description: 'Pagode Thien Mu, cuisine royale de Hué.' },
      { day: 9, title: 'Col des Nuages & Hoi An', description: 'Traversée du col des Nuages, arrivée à Hoi An.' },
      { day: 10, title: 'Hoi An - Vieille Ville', description: 'Pont japonais, maisons ancestrales, lanternes la nuit.' },
      { day: 11, title: 'Hoi An - Plage & Couture', description: 'Plage An Bang, atelier de couture sur mesure.' },
      { day: 12, title: 'Vol vers Ho Chi Minh', description: 'Découverte de la ville dynamique du Sud.' },
      { day: 13, title: 'Tunnels de Cu Chi', description: 'Réseau souterrain de la guerre du Vietnam.' },
      { day: 14, title: 'Delta du Mékong', description: 'Marchés flottants, villages sur pilotis.' },
      { day: 15, title: 'Ho Chi Minh - Dernière Journée', description: 'Marché Ben Thanh, Rue Bui Vien, derniers achats.' },
      { day: 16, title: 'Départ', description: 'Transfert et envol vers la France.' },
    ],
    is_featured: true,
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'mock-4',
    name: 'Thaïlande Complète',
    country: 'Thaïlande',
    description:
      'La Thaïlande, le "Pays du Sourire", offre une expérience de voyage incomparable. Ce circuit complet vous emmène de l\'effervescente Bangkok avec ses temples dorés et ses marchés nocturnes, jusqu\'aux îles paradisiaques de Koh Samui et Koh Phi Phi, en passant par la mystique Chiang Mai et ses éléphants. Vous serez conquis par la gentillesse du peuple thaïlandais, la richesse de leur culture et la diversité de leurs paysages.',
    short_description:
      'De Bangkok à Chiang Mai en passant par les îles paradisiaques, la Thaïlande dans toute sa diversité.',
    price: 2190,
    duration_days: 15,
    image_url: 'https://images.pexels.com/photos/1659438/pexels-photo-1659438.jpeg',
    gallery_urls: [
      'https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg',
      'https://images.pexels.com/photos/2049422/pexels-photo-2049422.jpeg',
      'https://images.pexels.com/photos/1450360/pexels-photo-1450360.jpeg',
    ],
    highlights: [
      'Grand Palais de Bangkok',
      'Sanctuaire des éléphants de Chiang Mai',
      'Plages de Koh Phi Phi',
      'Cours de cuisine thaïe',
      'Marché nocturne de Chiang Mai',
      'Plongée dans la mer d\'Andaman',
    ],
    program: [
      { day: 1, title: 'Arrivée à Bangkok', description: 'Installation et découverte du quartier de Khao San Road.' },
      { day: 2, title: 'Bangkok - Temples & Palais', description: 'Grand Palais, Wat Pho, Wat Arun et croisière sur le Chao Phraya.' },
      { day: 3, title: 'Bangkok - Marchés', description: 'Marché flottant de Damnoen Saduak et marché de Chatuchak.' },
      { day: 4, title: 'Ayutthaya', description: 'Ancienne capitale du royaume, temples et Bouddha à la tête dans les racines.' },
      { day: 5, title: 'Vol vers Chiang Mai', description: 'Arrivée et découverte du vieux quartier de Chiang Mai.' },
      { day: 6, title: 'Sanctuaire des Éléphants', description: 'Journée avec les éléphants dans un sanctuaire éthique.' },
      { day: 7, title: 'Trek & Villages', description: 'Trek dans les montagnes, villages Karen et chute d\'eau.' },
      { day: 8, title: 'Cuisine & Temple', description: 'Cours de cuisine thaïe et Doi Suthep au coucher du soleil.' },
      { day: 9, title: 'Vol vers les Îles', description: 'Arrivée à Koh Samui, plage de Chaweng.' },
      { day: 10, title: 'Koh Samui', description: 'Big Buddha, plongée en apnée et coucher de soleil.' },
      { day: 11, title: 'Koh Phi Phi', description: 'Excursion en bateau, Maya Bay et snorkeling.' },
      { day: 12, title: 'Krabi', description: 'Escalade à Railay Beach, kayak dans les mangroves.' },
      { day: 13, title: 'Journée Plage', description: 'Détente, massage thaïlandais et plongée.' },
      { day: 14, title: 'Retour Bangkok', description: 'Vol retour, shopping à MBK et soirée de gala.' },
      { day: 15, title: 'Départ', description: 'Transfert et envol vers la France.' },
    ],
    is_featured: false,
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'mock-5',
    name: 'Cambodge Mystérieux',
    country: 'Cambodge',
    description:
      'Le Cambodge est un pays qui fascine par la grandeur de son passé et la résilience de son peuple. Angkor Wat, la plus grande construction religieuse du monde, est le joyau de ce voyage, mais le Cambodge c\'est aussi Phnom Penh et son histoire tragique récente, le lac Tonlé Sap et ses villages flottants, les plages de Sihanoukville et la jungle sauvage des Cardamomes. Un voyage profondément humain et historique.',
    short_description:
      'Découvrez Angkor Wat et la richesse culturelle du Cambodge, entre temples majestueux et paysages authentiques.',
    price: 1690,
    duration_days: 11,
    image_url: 'https://images.pexels.com/photos/3290068/pexels-photo-3290068.jpeg',
    gallery_urls: [
      'https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg',
      'https://images.pexels.com/photos/1477430/pexels-photo-1477430.jpeg',
    ],
    highlights: [
      'Lever de soleil sur Angkor Wat',
      'Temples de Ta Prohm envahis par la jungle',
      'Villages flottants du Tonlé Sap',
      'Palais Royal de Phnom Penh',
      'Plages de Koh Rong',
      'Cuisine khmère',
    ],
    program: [
      { day: 1, title: 'Arrivée à Phnom Penh', description: 'Découverte de la capitale et du Palais Royal.' },
      { day: 2, title: 'Phnom Penh - Histoire', description: 'Musée national, Tuol Sleng et marché central.' },
      { day: 3, title: 'Vol vers Siem Reap', description: 'Arrivée et visite du village artisanal.' },
      { day: 4, title: 'Angkor Wat - Lever de Soleil', description: 'Lever de soleil sur Angkor, exploration du temple principal.' },
      { day: 5, title: 'Angkor Thom & Ta Prohm', description: 'Bayon, terrasse des éléphants et Ta Prohm envahi de lianes.' },
      { day: 6, title: 'Temples Éloignés', description: 'Banteay Srei et Preah Khan, moins fréquentés et très intacts.' },
      { day: 7, title: 'Tonlé Sap', description: 'Lac Tonlé Sap, villages flottants et coucher de soleil.' },
      { day: 8, title: 'Kampot & Pepper', description: 'Kampot et ses plantations de poivre, ville coloniale.' },
      { day: 9, title: 'Koh Rong', description: 'Île paradisiaque, plages de sable blanc et détente.' },
      { day: 10, title: 'Retour & Shopping', description: 'Retour à Siem Reap, marché nocturne et artisanat.' },
      { day: 11, title: 'Départ', description: 'Transfert à l\'aéroport et envol.' },
    ],
    is_featured: false,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 'mock-6',
    name: 'Sri Lanka en Liberté',
    country: 'Sri Lanka',
    description:
      'Surnommée la "Perle de l\'Océan Indien", Sri Lanka est une île aux mille visages. En seulement quelques heures de route, vous passerez de la savane aux éléphants aux forêts de thé à perte de vue, des plages de sable blanc aux temples bouddhistes troglodytes. Ce voyage vous plonge dans une culture ancienne et vivante, une gastronomie épicée et parfumée, et des paysages naturels d\'une beauté saisissante.',
    short_description:
      'La perle de l\'Océan Indien vous attend avec ses temples, ses jardins de thé, ses éléphants et ses plages.',
    price: 2090,
    duration_days: 13,
    image_url: 'https://images.pexels.com/photos/4353813/pexels-photo-4353813.jpeg',
    gallery_urls: [
      'https://images.pexels.com/photos/3889827/pexels-photo-3889827.jpeg',
      'https://images.pexels.com/photos/3408744/pexels-photo-3408744.jpeg',
    ],
    highlights: [
      'Rocher du Lion de Sigiriya',
      'Safari éléphants à Minneriya',
      'Plantation de thé de Nuwara Eliya',
      'Temple de la Dent de Bouddha à Kandy',
      'Train panoramique des montagnes',
      'Plages de Mirissa et baleines',
    ],
    program: [
      { day: 1, title: 'Arrivée à Colombo', description: 'Ville coloniale, Gangaramaya Temple et front de mer.' },
      { day: 2, title: 'Sigiriya - Forteresse du Lion', description: 'Ascension du rocher de Sigiriya et fresques rupestres.' },
      { day: 3, title: 'Polonnaruwa', description: 'Ancienne capitale, temples et statues de Bouddha.' },
      { day: 4, title: 'Safari Minneriya', description: 'Jeep safari et rassemblement des éléphants.' },
      { day: 5, title: 'Kandy', description: 'Temple de la Dent de Bouddha et spectacle de danse Kandyan.' },
      { day: 6, title: 'Jardins Botaniques', description: 'Peradeniya, plantation de thé et atelier de thé.' },
      { day: 7, title: 'Train des Montagnes', description: 'Trajet en train panoramique vers Ella.' },
      { day: 8, title: 'Ella & Randonnée', description: 'Little Adam\'s Peak, Nine Arch Bridge.' },
      { day: 9, title: 'Nuwara Eliya', description: 'Plantations de thé, Lake Gregory.' },
      { day: 10, title: 'Galle', description: 'Fort colonial, remparts, ruelle colorées.' },
      { day: 11, title: 'Mirissa', description: 'Observation des baleines bleues en mer.' },
      { day: 12, title: 'Plage & Détente', description: 'Snorkeling à Hikkaduwa et repos.' },
      { day: 13, title: 'Départ', description: 'Retour à Colombo et envol.' },
    ],
    is_featured: false,
    created_at: '2024-01-06T00:00:00Z',
    updated_at: '2024-01-06T00:00:00Z',
  },
];
